version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080


configuration:
  templates:
    - name: golang-middleware
      source: https://github.com/openfaas/golang-http-template

functions:
  status-echo:
    lang: golang-middleware
    handler: ./status-echo
    image: ghcr.io/${OWNER:-lucasroesler}/status-echo:${TAG:-latest}
  echo:
    lang: golang-middleware
    handler: ./echo
    image: ghcr.io/${OWNER:-lucasroesler}/echo:${TAG:-latest}
  nats-publisher:
    lang: golang-middleware
    handler: ./nats-publisher
    image: ghcr.io/${OWNER:-lucasroesler}/nats-publisher:${TAG:-latest}
    build-args:
      GO111MODULE: "on"
    environment:
      nats_url: nats://nats.openfaas:4222
  nats-receiver:
    lang: golang-middleware
    handler: ./nats-receiver
    image: ghcr.io/${OWNER:-lucasroesler}/nats-receiver:${TAG:-latest}
    annotations:
      topic: "nats-test"
