version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080


configuration:
  templates:
    - name: golang-middleware
      source: https://github.com/openfaas-incubator/golang-http-template
    - name: golang-http
      source: https://github.com/openfaas-incubator/golang-http-template

functions:
  status-echo:
    lang: golang-middleware
    handler: ./status-echo
    image: ghcr.io/${OWNER:-:lucasroesler}/status-echo:${TAG:-:latest}
  echo:
    lang: golang-http
    handler: ./echo
    image: ghcr.io/${OWNER:-:lucasroesler}/echo:${TAG:-:latest}
