
name: build

on:
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Get faas-cli
        run: curl -sLSf https://cli.openfaas.com | sudo sh
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Setup git-semver
        run: go get github.com/mdomke/git-semver
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get TAG
        id: get_tag
        run: echo ::set-output name=tag::$(git-semver)
      - name: Get Repo Owner
        id: get_repo_owner
        run: >
          echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} |
          tr '[:upper:]' '[:lower:]')
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ steps.get_repo_owner.outputs.repo_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
      - name: Publish functions
        run: >
          OWNER="${{ steps.get_repo_owner.outputs.repo_owner }}"
          TAG="${{ steps.get_tag.outputs.tag }}"
          faas-cli publish
          --extra-tag latest
          --platforms linux/amd64,linux/arm/v7,linux/arm64
